// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { GroupDB } from '../group-db'
import { GroupService } from '../group.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-groups-table',
  templateUrl: './groups-table.component.html',
  styleUrls: ['./groups-table.component.css'],
})
export class GroupsTableComponent implements OnInit {

  // used if the component is called as a selection component of Group instances
  selection: SelectionModel<GroupDB>;
  initialSelection = new Array<GroupDB>();

  // the data source for the table
  groups: GroupDB[];
  matTableDataSource: MatTableDataSource<GroupDB>


  // front repo, that will be referenced by this.groups
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private groupService: GroupService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of group instances
    public dialogRef: MatDialogRef<GroupsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.groupService.GroupServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getGroups()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Groups",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Groups",
      ]
      this.selection = new SelectionModel<GroupDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getGroups()
    this.matTableDataSource = new MatTableDataSource(this.groups)
  }

  getGroups(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.groups = this.frontRepo.Groups_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.groups.forEach(
            group => {
              let ID = this.dialogData.ID
              let revPointer = group[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(group)
              }
            }
          )
          this.selection = new SelectionModel<GroupDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.groups
      }
    )
  }

  // newGroup initiate a new group
  // create a new Group objet
  newGroup() {
  }

  deleteGroup(groupID: number, group: GroupDB) {
    // list of groups is truncated of group before the delete
    this.groups = this.groups.filter(h => h !== group);

    this.groupService.deleteGroup(groupID).subscribe(
      group => {
        this.groupService.GroupServiceChanged.next("delete")
      }
    );
  }

  editGroup(groupID: number, group: GroupDB) {

  }

  // display group in router
  displayGroupInRouter(groupID: number) {
    this.router.navigate(["group-display", groupID])
  }

  // set editor outlet
  setEditorRouterOutlet(groupID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["group-detail", groupID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(groupID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["group-presentation", groupID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.groups.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.groups.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<GroupDB>()

    // reset all initial selection of group that belong to group through Anarrayofb
    this.initialSelection.forEach(
      group => {
        group[this.dialogData.ReversePointer].Int64 = 0
        group[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(group)
      }
    )

    // from selection, set group that belong to group through Anarrayofb
    this.selection.selected.forEach(
      group => {
        let ID = +this.dialogData.ID
        group[this.dialogData.ReversePointer].Int64 = ID
        group[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(group)
      }
    )

    // update all group (only update selection & initial selection)
    toUpdate.forEach(
      group => {
        this.groupService.updateGroup(group)
          .subscribe(group => {
            this.groupService.GroupServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
