// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { LaneDB } from '../lane-db'
import { LaneService } from '../lane.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-lanes-table',
  templateUrl: './lanes-table.component.html',
  styleUrls: ['./lanes-table.component.css'],
})
export class LanesTableComponent implements OnInit {

  // used if the component is called as a selection component of Lane instances
  selection: SelectionModel<LaneDB>;
  initialSelection = new Array<LaneDB>();

  // the data source for the table
  lanes: LaneDB[];
  matTableDataSource: MatTableDataSource<LaneDB>


  // front repo, that will be referenced by this.lanes
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private laneService: LaneService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of lane instances
    public dialogRef: MatDialogRef<LanesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
    // this is for routerLink on same component when only queryParameter changes
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };

    // observable for changes in structs
    this.laneService.LaneServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getLanes()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Order",
        "Lanes",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Order",
        "Lanes",
      ]
      this.selection = new SelectionModel<LaneDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getLanes()
    this.matTableDataSource = new MatTableDataSource(this.lanes)
  }

  getLanes(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo
        console.log("front repo pull returned")

        this.lanes = this.frontRepo.Lanes_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.lanes.forEach(
            lane => {
              let ID = this.dialogData.ID
              let revPointer = lane[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(lane)
              }
            }
          )
          this.selection = new SelectionModel<LaneDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.lanes
      }
    )
  }

  // newLane initiate a new lane
  // create a new Lane objet
  newLane() {
  }

  deleteLane(laneID: number, lane: LaneDB) {
    // list of lanes is truncated of lane before the delete
    this.lanes = this.lanes.filter(h => h !== lane);

    this.laneService.deleteLane(laneID).subscribe(
      lane => {
        this.laneService.LaneServiceChanged.next("delete")

        console.log("lane deleted")
      }
    );
  }

  editLane(laneID: number, lane: LaneDB) {

  }

  // display lane in router
  displayLaneInRouter(laneID: number) {
    this.router.navigate(["lane-display", laneID])
  }

  // set editor outlet
  setEditorRouterOutlet(laneID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["lane-detail", laneID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(laneID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["lane-presentation", laneID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.lanes.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.lanes.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<LaneDB>()

    // reset all initial selection of lane that belong to lane through Anarrayofb
    this.initialSelection.forEach(
      lane => {
        lane[this.dialogData.ReversePointer].Int64 = 0
        lane[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(lane)
      }
    )

    // from selection, set lane that belong to lane through Anarrayofb
    this.selection.selected.forEach(
      lane => {
        console.log("selection ID " + lane.ID)
        let ID = +this.dialogData.ID
        lane[this.dialogData.ReversePointer].Int64 = ID
        lane[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(lane)
      }
    )

    // update all lane (only update selection & initial selection)
    toUpdate.forEach(
      lane => {
        this.laneService.updateLane(lane)
          .subscribe(lane => {
            this.laneService.LaneServiceChanged.next("update")
            console.log("lane saved")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
