// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { LaneDB } from '../lane-db'
import { LaneService } from '../lane.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-lanestable',
  templateUrl: './lanes-table.component.html',
  styleUrls: ['./lanes-table.component.css'],
})
export class LanesTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Lane instances
  selection: SelectionModel<LaneDB> = new (SelectionModel)
  initialSelection = new Array<LaneDB>()

  // the data source for the table
  lanes: LaneDB[] = []
  matTableDataSource: MatTableDataSource<LaneDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.lanes
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (laneDB: LaneDB, property: string) => {
      switch (property) {
        case 'ID':
          return laneDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return laneDB.Name;

        case 'Order':
          return laneDB.Order;

        case 'Gantt_Lanes':
          if (this.frontRepo.Gantts.get(laneDB.Gantt_LanesDBID.Int64) != undefined) {
            return this.frontRepo.Gantts.get(laneDB.Gantt_LanesDBID.Int64)!.Name
          } else {
            return ""
          }

        case 'Group_GroupLanes':
          if (this.frontRepo.Groups.get(laneDB.Group_GroupLanesDBID.Int64) != undefined) {
            return this.frontRepo.Groups.get(laneDB.Group_GroupLanesDBID.Int64)!.Name
          } else {
            return ""
          }

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (laneDB: LaneDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the laneDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += laneDB.Name.toLowerCase()
      mergedContent += laneDB.Order.toString()
      if (laneDB.Gantt_LanesDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Gantts.get(laneDB.Gantt_LanesDBID.Int64)!.Name.toLowerCase()
      }

      if (laneDB.Group_GroupLanesDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Groups.get(laneDB.Group_GroupLanesDBID.Int64)!.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private laneService: LaneService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of lane instances
    public dialogRef: MatDialogRef<LanesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.laneService.LaneServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getLanes()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Order",
        "Gantt_Lanes",
        "Group_GroupLanes",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Order",
        "Gantt_Lanes",
        "Group_GroupLanes",
      ]
      this.selection = new SelectionModel<LaneDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getLanes()
    this.matTableDataSource = new MatTableDataSource(this.lanes)
  }

  getLanes(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.lanes = this.frontRepo.Lanes_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let lane of this.lanes) {
            let ID = this.dialogData.ID
            let revPointer = lane[this.dialogData.ReversePointer as keyof LaneDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(lane)
            }
            this.selection = new SelectionModel<LaneDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, LaneDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as LaneDB[]
          for (let associationInstance of sourceField) {
            let lane = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as LaneDB
            this.initialSelection.push(lane)
          }

          this.selection = new SelectionModel<LaneDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.lanes
      }
    )
  }

  // newLane initiate a new lane
  // create a new Lane objet
  newLane() {
  }

  deleteLane(laneID: number, lane: LaneDB) {
    // list of lanes is truncated of lane before the delete
    this.lanes = this.lanes.filter(h => h !== lane);

    this.laneService.deleteLane(laneID).subscribe(
      lane => {
        this.laneService.LaneServiceChanged.next("delete")
      }
    );
  }

  editLane(laneID: number, lane: LaneDB) {

  }

  // display lane in router
  displayLaneInRouter(laneID: number) {
    this.router.navigate(["github_com_fullstack_lang_gonggantt_go-" + "lane-display", laneID])
  }

  // set editor outlet
  setEditorRouterOutlet(laneID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gonggantt_go_editor: ["github_com_fullstack_lang_gonggantt_go-" + "lane-detail", laneID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(laneID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gonggantt_go_presentation: ["github_com_fullstack_lang_gonggantt_go-" + "lane-presentation", laneID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.lanes.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.lanes.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<LaneDB>()

      // reset all initial selection of lane that belong to lane
      for (let lane of this.initialSelection) {
        let index = lane[this.dialogData.ReversePointer as keyof LaneDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(lane)

      }

      // from selection, set lane that belong to lane
      for (let lane of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = lane[this.dialogData.ReversePointer as keyof LaneDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(lane)
      }


      // update all lane (only update selection & initial selection)
      for (let lane of toUpdate) {
        this.laneService.updateLane(lane)
          .subscribe(lane => {
            this.laneService.LaneServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, LaneDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedLane = new Set<number>()
      for (let lane of this.initialSelection) {
        if (this.selection.selected.includes(lane)) {
          // console.log("lane " + lane.Name + " is still selected")
        } else {
          console.log("lane " + lane.Name + " has been unselected")
          unselectedLane.add(lane.ID)
          console.log("is unselected " + unselectedLane.has(lane.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let lane = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as LaneDB
      if (unselectedLane.has(lane.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<LaneDB>) = new Array<LaneDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          lane => {
            if (!this.initialSelection.includes(lane)) {
              // console.log("lane " + lane.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + lane.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = lane.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = lane.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("lane " + lane.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<LaneDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
