// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { ArrowDB } from '../arrow-db'
import { ArrowService } from '../arrow.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-arrowstable',
  templateUrl: './arrows-table.component.html',
  styleUrls: ['./arrows-table.component.css'],
})
export class ArrowsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Arrow instances
  selection: SelectionModel<ArrowDB> = new (SelectionModel)
  initialSelection = new Array<ArrowDB>()

  // the data source for the table
  arrows: ArrowDB[] = []
  matTableDataSource: MatTableDataSource<ArrowDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.arrows
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (arrowDB: ArrowDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return arrowDB.Name;

        case 'From':
          return (arrowDB.From ? arrowDB.From.Name : '');

        case 'To':
          return (arrowDB.To ? arrowDB.To.Name : '');

        case 'OptionnalColor':
          return arrowDB.OptionnalColor;

        case 'OptionnalStroke':
          return arrowDB.OptionnalStroke;

        case 'Gantt_Arrows':
          return this.frontRepo.Gantts.get(arrowDB.Gantt_ArrowsDBID.Int64)!.Name;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (arrowDB: ArrowDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the arrowDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += arrowDB.Name.toLowerCase()
      if (arrowDB.From) {
        mergedContent += arrowDB.From.Name.toLowerCase()
      }
      if (arrowDB.To) {
        mergedContent += arrowDB.To.Name.toLowerCase()
      }
      mergedContent += arrowDB.OptionnalColor.toLowerCase()
      mergedContent += arrowDB.OptionnalStroke.toLowerCase()
      if (arrowDB.Gantt_ArrowsDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Gantts.get(arrowDB.Gantt_ArrowsDBID.Int64)!.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private arrowService: ArrowService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of arrow instances
    public dialogRef: MatDialogRef<ArrowsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.arrowService.ArrowServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getArrows()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "From",
        "To",
        "OptionnalColor",
        "OptionnalStroke",
        "Gantt_Arrows",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "From",
        "To",
        "OptionnalColor",
        "OptionnalStroke",
        "Gantt_Arrows",
      ]
      this.selection = new SelectionModel<ArrowDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getArrows()
    this.matTableDataSource = new MatTableDataSource(this.arrows)
  }

  getArrows(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.arrows = this.frontRepo.Arrows_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let arrow of this.arrows) {
            let ID = this.dialogData.ID
            let revPointer = arrow[this.dialogData.ReversePointer as keyof ArrowDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(arrow)
            }
            this.selection = new SelectionModel<ArrowDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ArrowDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as ArrowDB[]
          for (let associationInstance of sourceField) {
            let arrow = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ArrowDB
            this.initialSelection.push(arrow)
          }

          this.selection = new SelectionModel<ArrowDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.arrows
      }
    )
  }

  // newArrow initiate a new arrow
  // create a new Arrow objet
  newArrow() {
  }

  deleteArrow(arrowID: number, arrow: ArrowDB) {
    // list of arrows is truncated of arrow before the delete
    this.arrows = this.arrows.filter(h => h !== arrow);

    this.arrowService.deleteArrow(arrowID).subscribe(
      arrow => {
        this.arrowService.ArrowServiceChanged.next("delete")
      }
    );
  }

  editArrow(arrowID: number, arrow: ArrowDB) {

  }

  // display arrow in router
  displayArrowInRouter(arrowID: number) {
    this.router.navigate(["github_com_fullstack_lang_gonggantt_go-" + "arrow-display", arrowID])
  }

  // set editor outlet
  setEditorRouterOutlet(arrowID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gonggantt_go_editor: ["github_com_fullstack_lang_gonggantt_go-" + "arrow-detail", arrowID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(arrowID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gonggantt_go_presentation: ["github_com_fullstack_lang_gonggantt_go-" + "arrow-presentation", arrowID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.arrows.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.arrows.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<ArrowDB>()

      // reset all initial selection of arrow that belong to arrow
      for (let arrow of this.initialSelection) {
        let index = arrow[this.dialogData.ReversePointer as keyof ArrowDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(arrow)

      }

      // from selection, set arrow that belong to arrow
      for (let arrow of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = arrow[this.dialogData.ReversePointer as keyof ArrowDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(arrow)
      }


      // update all arrow (only update selection & initial selection)
      for (let arrow of toUpdate) {
        this.arrowService.updateArrow(arrow)
          .subscribe(arrow => {
            this.arrowService.ArrowServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ArrowDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedArrow = new Set<number>()
      for (let arrow of this.initialSelection) {
        if (this.selection.selected.includes(arrow)) {
          // console.log("arrow " + arrow.Name + " is still selected")
        } else {
          console.log("arrow " + arrow.Name + " has been unselected")
          unselectedArrow.add(arrow.ID)
          console.log("is unselected " + unselectedArrow.has(arrow.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let arrow = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ArrowDB
      if (unselectedArrow.has(arrow.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<ArrowDB>) = new Array<ArrowDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          arrow => {
            if (!this.initialSelection.includes(arrow)) {
              // console.log("arrow " + arrow.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + arrow.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = arrow.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = arrow.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("arrow " + arrow.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<ArrowDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
