// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"github.com/fullstack-lang/gonggantt/go/models"
	"github.com/fullstack-lang/gonggantt/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __LaneUse__dummysDeclaration__ models.LaneUse
var __LaneUse_time__dummyDeclaration time.Duration

// An LaneUseID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getLaneUse updateLaneUse deleteLaneUse
type LaneUseID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// LaneUseInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postLaneUse updateLaneUse
type LaneUseInput struct {
	// The LaneUse to submit or modify
	// in: body
	LaneUse *orm.LaneUseAPI
}

// GetLaneUses
//
// swagger:route GET /laneuses laneuses getLaneUses
//
// # Get all laneuses
//
// Responses:
// default: genericError
//
//	200: laneuseDBResponse
func GetLaneUses(c *gin.Context) {
	db := orm.BackRepo.BackRepoLaneUse.GetDB()

	// source slice
	var laneuseDBs []orm.LaneUseDB
	query := db.Find(&laneuseDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	laneuseAPIs := make([]orm.LaneUseAPI, 0)

	// for each laneuse, update fields from the database nullable fields
	for idx := range laneuseDBs {
		laneuseDB := &laneuseDBs[idx]
		_ = laneuseDB
		var laneuseAPI orm.LaneUseAPI

		// insertion point for updating fields
		laneuseAPI.ID = laneuseDB.ID
		laneuseDB.CopyBasicFieldsToLaneUse(&laneuseAPI.LaneUse)
		laneuseAPI.LaneUsePointersEnconding = laneuseDB.LaneUsePointersEnconding
		laneuseAPIs = append(laneuseAPIs, laneuseAPI)
	}

	c.JSON(http.StatusOK, laneuseAPIs)
}

// PostLaneUse
//
// swagger:route POST /laneuses laneuses postLaneUse
//
// Creates a laneuse
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func PostLaneUse(c *gin.Context) {
	db := orm.BackRepo.BackRepoLaneUse.GetDB()

	// Validate input
	var input orm.LaneUseAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create laneuse
	laneuseDB := orm.LaneUseDB{}
	laneuseDB.LaneUsePointersEnconding = input.LaneUsePointersEnconding
	laneuseDB.CopyBasicFieldsFromLaneUse(&input.LaneUse)

	query := db.Create(&laneuseDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	orm.BackRepo.BackRepoLaneUse.CheckoutPhaseOneInstance(&laneuseDB)
	laneuse := (*orm.BackRepo.BackRepoLaneUse.Map_LaneUseDBID_LaneUsePtr)[laneuseDB.ID]

	if laneuse != nil {
		models.AfterCreateFromFront(&models.Stage, laneuse)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, laneuseDB)
}

// GetLaneUse
//
// swagger:route GET /laneuses/{ID} laneuses getLaneUse
//
// Gets the details for a laneuse.
//
// Responses:
// default: genericError
//
//	200: laneuseDBResponse
func GetLaneUse(c *gin.Context) {
	db := orm.BackRepo.BackRepoLaneUse.GetDB()

	// Get laneuseDB in DB
	var laneuseDB orm.LaneUseDB
	if err := db.First(&laneuseDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var laneuseAPI orm.LaneUseAPI
	laneuseAPI.ID = laneuseDB.ID
	laneuseAPI.LaneUsePointersEnconding = laneuseDB.LaneUsePointersEnconding
	laneuseDB.CopyBasicFieldsToLaneUse(&laneuseAPI.LaneUse)

	c.JSON(http.StatusOK, laneuseAPI)
}

// UpdateLaneUse
//
// swagger:route PATCH /laneuses/{ID} laneuses updateLaneUse
//
// # Update a laneuse
//
// Responses:
// default: genericError
//
//	200: laneuseDBResponse
func UpdateLaneUse(c *gin.Context) {
	db := orm.BackRepo.BackRepoLaneUse.GetDB()

	// Get model if exist
	var laneuseDB orm.LaneUseDB

	// fetch the laneuse
	query := db.First(&laneuseDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.LaneUseAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	laneuseDB.CopyBasicFieldsFromLaneUse(&input.LaneUse)
	laneuseDB.LaneUsePointersEnconding = input.LaneUsePointersEnconding

	query = db.Model(&laneuseDB).Updates(laneuseDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	laneuseNew := new(models.LaneUse)
	laneuseDB.CopyBasicFieldsToLaneUse(laneuseNew)

	// get stage instance from DB instance, and call callback function
	laneuseOld := (*orm.BackRepo.BackRepoLaneUse.Map_LaneUseDBID_LaneUsePtr)[laneuseDB.ID]
	if laneuseOld != nil {
		models.AfterUpdateFromFront(&models.Stage, laneuseOld, laneuseNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the laneuseDB
	c.JSON(http.StatusOK, laneuseDB)
}

// DeleteLaneUse
//
// swagger:route DELETE /laneuses/{ID} laneuses deleteLaneUse
//
// # Delete a laneuse
//
// default: genericError
//
//	200: laneuseDBResponse
func DeleteLaneUse(c *gin.Context) {
	db := orm.BackRepo.BackRepoLaneUse.GetDB()

	// Get model if exist
	var laneuseDB orm.LaneUseDB
	if err := db.First(&laneuseDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&laneuseDB)

	// get an instance (not staged) from DB instance, and call callback function
	laneuseDeleted := new(models.LaneUse)
	laneuseDB.CopyBasicFieldsToLaneUse(laneuseDeleted)

	// get stage instance from DB instance, and call callback function
	laneuseStaged := (*orm.BackRepo.BackRepoLaneUse.Map_LaneUseDBID_LaneUsePtr)[laneuseDB.ID]
	if laneuseStaged != nil {
		models.AfterDeleteFromFront(&models.Stage, laneuseStaged, laneuseDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
