// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ArrowDB } from './arrow-db';

// insertion point for imports
import { BarDB } from './bar-db'
import { GanttDB } from './gantt-db'

@Injectable({
  providedIn: 'root'
})
export class ArrowService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ArrowServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private arrowsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.arrowsUrl = origin + '/api/github.com/fullstack-lang/gonggantt/go/v1/arrows';
  }

  /** GET arrows from the server */
  getArrows(GONG__StackPath: string): Observable<ArrowDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<ArrowDB[]>(this.arrowsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched arrows')),
        catchError(this.handleError<ArrowDB[]>('getArrows', []))
      );
  }

  /** GET arrow by id. Will 404 if id not found */
  getArrow(id: number, GONG__StackPath: string): Observable<ArrowDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.arrowsUrl}/${id}`;
    return this.http.get<ArrowDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched arrow id=${id}`)),
      catchError(this.handleError<ArrowDB>(`getArrow id=${id}`))
    );
  }

  /** POST: add a new arrow to the server */
  postArrow(arrowdb: ArrowDB, GONG__StackPath: string): Observable<ArrowDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    arrowdb.From = new BarDB
    arrowdb.To = new BarDB
    let _Gantt_Arrows_reverse = arrowdb.Gantt_Arrows_reverse
    arrowdb.Gantt_Arrows_reverse = new GanttDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ArrowDB>(this.arrowsUrl, arrowdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        arrowdb.Gantt_Arrows_reverse = _Gantt_Arrows_reverse
        // this.log(`posted arrowdb id=${arrowdb.ID}`)
      }),
      catchError(this.handleError<ArrowDB>('postArrow'))
    );
  }

  /** DELETE: delete the arrowdb from the server */
  deleteArrow(arrowdb: ArrowDB | number, GONG__StackPath: string): Observable<ArrowDB> {
    const id = typeof arrowdb === 'number' ? arrowdb : arrowdb.ID;
    const url = `${this.arrowsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<ArrowDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted arrowdb id=${id}`)),
      catchError(this.handleError<ArrowDB>('deleteArrow'))
    );
  }

  /** PUT: update the arrowdb on the server */
  updateArrow(arrowdb: ArrowDB, GONG__StackPath: string): Observable<ArrowDB> {
    const id = typeof arrowdb === 'number' ? arrowdb : arrowdb.ID;
    const url = `${this.arrowsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    arrowdb.From = new BarDB
    arrowdb.To = new BarDB
    let _Gantt_Arrows_reverse = arrowdb.Gantt_Arrows_reverse
    arrowdb.Gantt_Arrows_reverse = new GanttDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<ArrowDB>(url, arrowdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        arrowdb.Gantt_Arrows_reverse = _Gantt_Arrows_reverse
        // this.log(`updated arrowdb id=${arrowdb.ID}`)
      }),
      catchError(this.handleError<ArrowDB>('updateArrow'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in ArrowService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("ArrowService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
