// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { GanttAPI } from './gantt-api';
import { GanttDB } from './gantt-db';

@Injectable({
  providedIn: 'root'
})
export class GanttService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  GanttServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private ganttsUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gonggantt/go/v1/gantts';

  constructor(
    private http: HttpClient
  ) { }

  /** GET gantts from the server */
  getGantts(): Observable<GanttDB[]> {
    return this.http.get<GanttDB[]>(this.ganttsUrl)
      .pipe(
        tap(_ => this.log('fetched gantts')),
        catchError(this.handleError<GanttDB[]>('getGantts', []))
      );
  }

  /** GET gantt by id. Will 404 if id not found */
  getGantt(id: number): Observable<GanttDB> {
    const url = `${this.ganttsUrl}/${id}`;
    return this.http.get<GanttDB>(url).pipe(
      tap(_ => this.log(`fetched gantt id=${id}`)),
      catchError(this.handleError<GanttDB>(`getGantt id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new gantt to the server */
  postGantt(ganttdb: GanttDB): Observable<GanttDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    ganttdb.Lanes = []
    ganttdb.Milestones = []
    ganttdb.Groups = []

		return this.http.post<GanttDB>(this.ganttsUrl, ganttdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted ganttdb id=${ganttdb.ID}`)
			}),
			catchError(this.handleError<GanttDB>('postGantt'))
		);
  }

  /** DELETE: delete the ganttdb from the server */
  deleteGantt(ganttdb: GanttDB | number): Observable<GanttDB> {
    const id = typeof ganttdb === 'number' ? ganttdb : ganttdb.ID;
    const url = `${this.ganttsUrl}/${id}`;

    return this.http.delete<GanttDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted ganttdb id=${id}`)),
      catchError(this.handleError<GanttDB>('deleteGantt'))
    );
  }

  /** PUT: update the ganttdb on the server */
  updateGantt(ganttdb: GanttDB): Observable<GanttDB> {
    const id = typeof ganttdb === 'number' ? ganttdb : ganttdb.ID;
    const url = `${this.ganttsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    ganttdb.Lanes = []
    ganttdb.Milestones = []
    ganttdb.Groups = []

    return this.http.put(url, ganttdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated ganttdb id=${ganttdb.ID}`)
      }),
      catchError(this.handleError<GanttDB>('updateGantt'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
