// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { GanttDB } from './gantt-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class GanttService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  GanttServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private ganttsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.ganttsUrl = origin + '/api/github.com/fullstack-lang/gonggantt/go/v1/gantts';
  }

  /** GET gantts from the server */
  getGantts(GONG__StackPath: string): Observable<GanttDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<GanttDB[]>(this.ganttsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched gantts')),
        catchError(this.handleError<GanttDB[]>('getGantts', []))
      );
  }

  /** GET gantt by id. Will 404 if id not found */
  getGantt(id: number, GONG__StackPath: string): Observable<GanttDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.ganttsUrl}/${id}`;
    return this.http.get<GanttDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched gantt id=${id}`)),
      catchError(this.handleError<GanttDB>(`getGantt id=${id}`))
    );
  }

  /** POST: add a new gantt to the server */
  postGantt(ganttdb: GanttDB, GONG__StackPath: string): Observable<GanttDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    ganttdb.Lanes = []
    ganttdb.Milestones = []
    ganttdb.Groups = []
    ganttdb.Arrows = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<GanttDB>(this.ganttsUrl, ganttdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted ganttdb id=${ganttdb.ID}`)
      }),
      catchError(this.handleError<GanttDB>('postGantt'))
    );
  }

  /** DELETE: delete the ganttdb from the server */
  deleteGantt(ganttdb: GanttDB | number, GONG__StackPath: string): Observable<GanttDB> {
    const id = typeof ganttdb === 'number' ? ganttdb : ganttdb.ID;
    const url = `${this.ganttsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<GanttDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted ganttdb id=${id}`)),
      catchError(this.handleError<GanttDB>('deleteGantt'))
    );
  }

  /** PUT: update the ganttdb on the server */
  updateGantt(ganttdb: GanttDB, GONG__StackPath: string): Observable<GanttDB> {
    const id = typeof ganttdb === 'number' ? ganttdb : ganttdb.ID;
    const url = `${this.ganttsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    ganttdb.Lanes = []
    ganttdb.Milestones = []
    ganttdb.Groups = []
    ganttdb.Arrows = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<GanttDB>(url, ganttdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated ganttdb id=${ganttdb.ID}`)
      }),
      catchError(this.handleError<GanttDB>('updateGantt'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in GanttService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("GanttService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
