// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { GroupDB } from './group-db';

// insertion point for imports
import { GanttDB } from './gantt-db'

@Injectable({
  providedIn: 'root'
})
export class GroupService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  GroupServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private groupsUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.groupsUrl = origin + '/api/github.com/fullstack-lang/gonggantt/go/v1/groups';
  }

  /** GET groups from the server */
  getGroups(): Observable<GroupDB[]> {
    return this.http.get<GroupDB[]>(this.groupsUrl)
      .pipe(
        tap(_ => this.log('fetched groups')),
        catchError(this.handleError<GroupDB[]>('getGroups', []))
      );
  }

  /** GET group by id. Will 404 if id not found */
  getGroup(id: number): Observable<GroupDB> {
    const url = `${this.groupsUrl}/${id}`;
    return this.http.get<GroupDB>(url).pipe(
      tap(_ => this.log(`fetched group id=${id}`)),
      catchError(this.handleError<GroupDB>(`getGroup id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new group to the server */
  postGroup(groupdb: GroupDB): Observable<GroupDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    groupdb.GroupLanes = []
    let _Gantt_Groups_reverse = groupdb.Gantt_Groups_reverse
    groupdb.Gantt_Groups_reverse = new GanttDB

    return this.http.post<GroupDB>(this.groupsUrl, groupdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        groupdb.Gantt_Groups_reverse = _Gantt_Groups_reverse
        this.log(`posted groupdb id=${groupdb.ID}`)
      }),
      catchError(this.handleError<GroupDB>('postGroup'))
    );
  }

  /** DELETE: delete the groupdb from the server */
  deleteGroup(groupdb: GroupDB | number): Observable<GroupDB> {
    const id = typeof groupdb === 'number' ? groupdb : groupdb.ID;
    const url = `${this.groupsUrl}/${id}`;

    return this.http.delete<GroupDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted groupdb id=${id}`)),
      catchError(this.handleError<GroupDB>('deleteGroup'))
    );
  }

  /** PUT: update the groupdb on the server */
  updateGroup(groupdb: GroupDB): Observable<GroupDB> {
    const id = typeof groupdb === 'number' ? groupdb : groupdb.ID;
    const url = `${this.groupsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    groupdb.GroupLanes = []
    let _Gantt_Groups_reverse = groupdb.Gantt_Groups_reverse
    groupdb.Gantt_Groups_reverse = new GanttDB

    return this.http.put<GroupDB>(url, groupdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        groupdb.Gantt_Groups_reverse = _Gantt_Groups_reverse
        this.log(`updated groupdb id=${groupdb.ID}`)
      }),
      catchError(this.handleError<GroupDB>('updateGroup'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
