// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { LaneAPI } from './lane-api';
import { LaneDB } from './lane-db';

@Injectable({
  providedIn: 'root'
})
export class LaneService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  LaneServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private lanesUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gonggantt/go/v1/lanes';

  constructor(
    private http: HttpClient
  ) { }

  /** GET lanes from the server */
  getLanes(): Observable<LaneDB[]> {
    return this.http.get<LaneDB[]>(this.lanesUrl)
      .pipe(
        tap(_ => this.log('fetched lanes')),
        catchError(this.handleError<LaneDB[]>('getLanes', []))
      );
  }

  /** GET lane by id. Will 404 if id not found */
  getLane(id: number): Observable<LaneDB> {
    const url = `${this.lanesUrl}/${id}`;
    return this.http.get<LaneDB>(url).pipe(
      tap(_ => this.log(`fetched lane id=${id}`)),
      catchError(this.handleError<LaneDB>(`getLane id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new lane to the server */
  postLane(lanedb: LaneDB): Observable<LaneDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    lanedb.Bars = []
    let _Gantt_Lanes_reverse = lanedb.Gantt_Lanes_reverse
    lanedb.Gantt_Lanes_reverse = {}
    let _Group_GroupLanes_reverse = lanedb.Group_GroupLanes_reverse
    lanedb.Group_GroupLanes_reverse = {}
    let _Milestone_DiamonfAndTextAnchors_reverse = lanedb.Milestone_DiamonfAndTextAnchors_reverse
    lanedb.Milestone_DiamonfAndTextAnchors_reverse = {}

		return this.http.post<LaneDB>(this.lanesUrl, lanedb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
        lanedb.Gantt_Lanes_reverse = _Gantt_Lanes_reverse
        lanedb.Group_GroupLanes_reverse = _Group_GroupLanes_reverse
        lanedb.Milestone_DiamonfAndTextAnchors_reverse = _Milestone_DiamonfAndTextAnchors_reverse
				this.log(`posted lanedb id=${lanedb.ID}`)
			}),
			catchError(this.handleError<LaneDB>('postLane'))
		);
  }

  /** DELETE: delete the lanedb from the server */
  deleteLane(lanedb: LaneDB | number): Observable<LaneDB> {
    const id = typeof lanedb === 'number' ? lanedb : lanedb.ID;
    const url = `${this.lanesUrl}/${id}`;

    return this.http.delete<LaneDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted lanedb id=${id}`)),
      catchError(this.handleError<LaneDB>('deleteLane'))
    );
  }

  /** PUT: update the lanedb on the server */
  updateLane(lanedb: LaneDB): Observable<LaneDB> {
    const id = typeof lanedb === 'number' ? lanedb : lanedb.ID;
    const url = `${this.lanesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    lanedb.Bars = []
    let _Gantt_Lanes_reverse = lanedb.Gantt_Lanes_reverse
    lanedb.Gantt_Lanes_reverse = {}
    let _Group_GroupLanes_reverse = lanedb.Group_GroupLanes_reverse
    lanedb.Group_GroupLanes_reverse = {}
    let _Milestone_DiamonfAndTextAnchors_reverse = lanedb.Milestone_DiamonfAndTextAnchors_reverse
    lanedb.Milestone_DiamonfAndTextAnchors_reverse = {}

    return this.http.put(url, lanedb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        lanedb.Gantt_Lanes_reverse = _Gantt_Lanes_reverse
        lanedb.Group_GroupLanes_reverse = _Group_GroupLanes_reverse
        lanedb.Milestone_DiamonfAndTextAnchors_reverse = _Milestone_DiamonfAndTextAnchors_reverse
        this.log(`updated lanedb id=${lanedb.ID}`)
      }),
      catchError(this.handleError<LaneDB>('updateLane'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
