// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { LaneDB } from './lane-db';

// insertion point for imports
import { GanttDB } from './gantt-db'
import { GroupDB } from './group-db'
import { MilestoneDB } from './milestone-db'

@Injectable({
  providedIn: 'root'
})
export class LaneService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  LaneServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private lanesUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.lanesUrl = origin + '/api/github.com/fullstack-lang/gonggantt/go/v1/lanes';
  }

  /** GET lanes from the server */
  getLanes(): Observable<LaneDB[]> {
    return this.http.get<LaneDB[]>(this.lanesUrl)
      .pipe(
        tap(_ => this.log('fetched lanes')),
        catchError(this.handleError<LaneDB[]>('getLanes', []))
      );
  }

  /** GET lane by id. Will 404 if id not found */
  getLane(id: number): Observable<LaneDB> {
    const url = `${this.lanesUrl}/${id}`;
    return this.http.get<LaneDB>(url).pipe(
      tap(_ => this.log(`fetched lane id=${id}`)),
      catchError(this.handleError<LaneDB>(`getLane id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new lane to the server */
  postLane(lanedb: LaneDB): Observable<LaneDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    lanedb.Bars = []
    let _Gantt_Lanes_reverse = lanedb.Gantt_Lanes_reverse
    lanedb.Gantt_Lanes_reverse = new GanttDB
    let _Group_GroupLanes_reverse = lanedb.Group_GroupLanes_reverse
    lanedb.Group_GroupLanes_reverse = new GroupDB
    let _Milestone_DiamonfAndTextAnchors_reverse = lanedb.Milestone_DiamonfAndTextAnchors_reverse
    lanedb.Milestone_DiamonfAndTextAnchors_reverse = new MilestoneDB

    return this.http.post<LaneDB>(this.lanesUrl, lanedb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        lanedb.Gantt_Lanes_reverse = _Gantt_Lanes_reverse
        lanedb.Group_GroupLanes_reverse = _Group_GroupLanes_reverse
        lanedb.Milestone_DiamonfAndTextAnchors_reverse = _Milestone_DiamonfAndTextAnchors_reverse
        this.log(`posted lanedb id=${lanedb.ID}`)
      }),
      catchError(this.handleError<LaneDB>('postLane'))
    );
  }

  /** DELETE: delete the lanedb from the server */
  deleteLane(lanedb: LaneDB | number): Observable<LaneDB> {
    const id = typeof lanedb === 'number' ? lanedb : lanedb.ID;
    const url = `${this.lanesUrl}/${id}`;

    return this.http.delete<LaneDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted lanedb id=${id}`)),
      catchError(this.handleError<LaneDB>('deleteLane'))
    );
  }

  /** PUT: update the lanedb on the server */
  updateLane(lanedb: LaneDB): Observable<LaneDB> {
    const id = typeof lanedb === 'number' ? lanedb : lanedb.ID;
    const url = `${this.lanesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    lanedb.Bars = []
    let _Gantt_Lanes_reverse = lanedb.Gantt_Lanes_reverse
    lanedb.Gantt_Lanes_reverse = new GanttDB
    let _Group_GroupLanes_reverse = lanedb.Group_GroupLanes_reverse
    lanedb.Group_GroupLanes_reverse = new GroupDB
    let _Milestone_DiamonfAndTextAnchors_reverse = lanedb.Milestone_DiamonfAndTextAnchors_reverse
    lanedb.Milestone_DiamonfAndTextAnchors_reverse = new MilestoneDB

    return this.http.put<LaneDB>(url, lanedb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        lanedb.Gantt_Lanes_reverse = _Gantt_Lanes_reverse
        lanedb.Group_GroupLanes_reverse = _Group_GroupLanes_reverse
        lanedb.Milestone_DiamonfAndTextAnchors_reverse = _Milestone_DiamonfAndTextAnchors_reverse
        this.log(`updated lanedb id=${lanedb.ID}`)
      }),
      catchError(this.handleError<LaneDB>('updateLane'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
