// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { LaneUseDB } from './laneuse-db';

// insertion point for imports
import { LaneDB } from './lane-db'
import { MilestoneDB } from './milestone-db'

@Injectable({
  providedIn: 'root'
})
export class LaneUseService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  LaneUseServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private laneusesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.laneusesUrl = origin + '/api/github.com/fullstack-lang/gonggantt/go/v1/laneuses';
  }

  /** GET laneuses from the server */
  getLaneUses(GONG__StackPath: string = ""): Observable<LaneUseDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<LaneUseDB[]>(this.laneusesUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched laneuses')),
        catchError(this.handleError<LaneUseDB[]>('getLaneUses', []))
      );
  }

  /** GET laneuse by id. Will 404 if id not found */
  getLaneUse(id: number): Observable<LaneUseDB> {
    const url = `${this.laneusesUrl}/${id}`;
    return this.http.get<LaneUseDB>(url).pipe(
      tap(_ => this.log(`fetched laneuse id=${id}`)),
      catchError(this.handleError<LaneUseDB>(`getLaneUse id=${id}`))
    );
  }

  /** POST: add a new laneuse to the server */
  postLaneUse(laneusedb: LaneUseDB, GONG__StackPath: string): Observable<LaneUseDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    laneusedb.Lane = new LaneDB
    let _Milestone_LanesToDisplayMilestoneUse_reverse = laneusedb.Milestone_LanesToDisplayMilestoneUse_reverse
    laneusedb.Milestone_LanesToDisplayMilestoneUse_reverse = new MilestoneDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<LaneUseDB>(this.laneusesUrl, laneusedb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        laneusedb.Milestone_LanesToDisplayMilestoneUse_reverse = _Milestone_LanesToDisplayMilestoneUse_reverse
        this.log(`posted laneusedb id=${laneusedb.ID}`)
      }),
      catchError(this.handleError<LaneUseDB>('postLaneUse'))
    );
  }

  /** DELETE: delete the laneusedb from the server */
  deleteLaneUse(laneusedb: LaneUseDB | number, GONG__StackPath: string): Observable<LaneUseDB> {
    const id = typeof laneusedb === 'number' ? laneusedb : laneusedb.ID;
    const url = `${this.laneusesUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<LaneUseDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted laneusedb id=${id}`)),
      catchError(this.handleError<LaneUseDB>('deleteLaneUse'))
    );
  }

  /** PUT: update the laneusedb on the server */
  updateLaneUse(laneusedb: LaneUseDB, GONG__StackPath: string): Observable<LaneUseDB> {
    const id = typeof laneusedb === 'number' ? laneusedb : laneusedb.ID;
    const url = `${this.laneusesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    laneusedb.Lane = new LaneDB
    let _Milestone_LanesToDisplayMilestoneUse_reverse = laneusedb.Milestone_LanesToDisplayMilestoneUse_reverse
    laneusedb.Milestone_LanesToDisplayMilestoneUse_reverse = new MilestoneDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<LaneUseDB>(url, laneusedb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        laneusedb.Milestone_LanesToDisplayMilestoneUse_reverse = _Milestone_LanesToDisplayMilestoneUse_reverse
        this.log(`updated laneusedb id=${laneusedb.ID}`)
      }),
      catchError(this.handleError<LaneUseDB>('updateLaneUse'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in LaneUseService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("LaneUseService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
