// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { MilestoneDB } from '../milestone-db'
import { MilestoneService } from '../milestone.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-milestones-table',
  templateUrl: './milestones-table.component.html',
  styleUrls: ['./milestones-table.component.css'],
})
export class MilestonesTableComponent implements OnInit {

  // used if the component is called as a selection component of Milestone instances
  selection: SelectionModel<MilestoneDB>;
  initialSelection = new Array<MilestoneDB>();

  // the data source for the table
  milestones: MilestoneDB[];
  matTableDataSource: MatTableDataSource<MilestoneDB>


  // front repo, that will be referenced by this.milestones
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private milestoneService: MilestoneService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of milestone instances
    public dialogRef: MatDialogRef<MilestonesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
    // this is for routerLink on same component when only queryParameter changes
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };

    // observable for changes in structs
    this.milestoneService.MilestoneServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getMilestones()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Date",
        "Milestones",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Date",
        "Milestones",
      ]
      this.selection = new SelectionModel<MilestoneDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getMilestones()
    this.matTableDataSource = new MatTableDataSource(this.milestones)
  }

  getMilestones(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo
        console.log("front repo pull returned")

        this.milestones = this.frontRepo.Milestones_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.milestones.forEach(
            milestone => {
              let ID = this.dialogData.ID
              let revPointer = milestone[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(milestone)
              }
            }
          )
          this.selection = new SelectionModel<MilestoneDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.milestones
      }
    )
  }

  // newMilestone initiate a new milestone
  // create a new Milestone objet
  newMilestone() {
  }

  deleteMilestone(milestoneID: number, milestone: MilestoneDB) {
    // list of milestones is truncated of milestone before the delete
    this.milestones = this.milestones.filter(h => h !== milestone);

    this.milestoneService.deleteMilestone(milestoneID).subscribe(
      milestone => {
        this.milestoneService.MilestoneServiceChanged.next("delete")

        console.log("milestone deleted")
      }
    );
  }

  editMilestone(milestoneID: number, milestone: MilestoneDB) {

  }

  // display milestone in router
  displayMilestoneInRouter(milestoneID: number) {
    this.router.navigate(["milestone-display", milestoneID])
  }

  // set editor outlet
  setEditorRouterOutlet(milestoneID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["milestone-detail", milestoneID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(milestoneID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["milestone-presentation", milestoneID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.milestones.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.milestones.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<MilestoneDB>()

    // reset all initial selection of milestone that belong to milestone through Anarrayofb
    this.initialSelection.forEach(
      milestone => {
        milestone[this.dialogData.ReversePointer].Int64 = 0
        milestone[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(milestone)
      }
    )

    // from selection, set milestone that belong to milestone through Anarrayofb
    this.selection.selected.forEach(
      milestone => {
        console.log("selection ID " + milestone.ID)
        let ID = +this.dialogData.ID
        milestone[this.dialogData.ReversePointer].Int64 = ID
        milestone[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(milestone)
      }
    )

    // update all milestone (only update selection & initial selection)
    toUpdate.forEach(
      milestone => {
        this.milestoneService.updateMilestone(milestone)
          .subscribe(milestone => {
            this.milestoneService.MilestoneServiceChanged.next("update")
            console.log("milestone saved")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
