// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { LaneUseDB } from '../laneuse-db'
import { LaneUseService } from '../laneuse.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-laneusestable',
  templateUrl: './laneuses-table.component.html',
  styleUrls: ['./laneuses-table.component.css'],
})
export class LaneUsesTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of LaneUse instances
  selection: SelectionModel<LaneUseDB> = new (SelectionModel)
  initialSelection = new Array<LaneUseDB>()

  // the data source for the table
  laneuses: LaneUseDB[] = []
  matTableDataSource: MatTableDataSource<LaneUseDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.laneuses
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (laneuseDB: LaneUseDB, property: string) => {
      switch (property) {
        case 'ID':
          return laneuseDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return laneuseDB.Name;

        case 'Lane':
          return (laneuseDB.Lane ? laneuseDB.Lane.Name : '');

        case 'Milestone_LanesToDisplayMilestoneUse':
          if (this.frontRepo.Milestones.get(laneuseDB.Milestone_LanesToDisplayMilestoneUseDBID.Int64) != undefined) {
            return this.frontRepo.Milestones.get(laneuseDB.Milestone_LanesToDisplayMilestoneUseDBID.Int64)!.Name
          } else {
            return ""
          }

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (laneuseDB: LaneUseDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the laneuseDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += laneuseDB.Name.toLowerCase()
      if (laneuseDB.Lane) {
        mergedContent += laneuseDB.Lane.Name.toLowerCase()
      }
      if (laneuseDB.Milestone_LanesToDisplayMilestoneUseDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Milestones.get(laneuseDB.Milestone_LanesToDisplayMilestoneUseDBID.Int64)!.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private laneuseService: LaneUseService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of laneuse instances
    public dialogRef: MatDialogRef<LaneUsesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.laneuseService.LaneUseServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getLaneUses()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "Lane",
        "Milestone_LanesToDisplayMilestoneUse",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Lane",
        "Milestone_LanesToDisplayMilestoneUse",
      ]
      this.selection = new SelectionModel<LaneUseDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if ( stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getLaneUses()

    this.matTableDataSource = new MatTableDataSource(this.laneuses)
  }

  getLaneUses(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.laneuses = this.frontRepo.LaneUses_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let laneuse of this.laneuses) {
            let ID = this.dialogData.ID
            let revPointer = laneuse[this.dialogData.ReversePointer as keyof LaneUseDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(laneuse)
            }
            this.selection = new SelectionModel<LaneUseDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, LaneUseDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as LaneUseDB[]
          for (let associationInstance of sourceField) {
            let laneuse = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as LaneUseDB
            this.initialSelection.push(laneuse)
          }

          this.selection = new SelectionModel<LaneUseDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.laneuses
      }
    )
  }

  // newLaneUse initiate a new laneuse
  // create a new LaneUse objet
  newLaneUse() {
  }

  deleteLaneUse(laneuseID: number, laneuse: LaneUseDB) {
    // list of laneuses is truncated of laneuse before the delete
    this.laneuses = this.laneuses.filter(h => h !== laneuse);

    this.laneuseService.deleteLaneUse(laneuseID).subscribe(
      laneuse => {
        this.laneuseService.LaneUseServiceChanged.next("delete")
      }
    );
  }

  editLaneUse(laneuseID: number, laneuse: LaneUseDB) {

  }

  // display laneuse in router
  displayLaneUseInRouter(laneuseID: number) {
    this.router.navigate(["github_com_fullstack_lang_gonggantt_go-" + "laneuse-display", laneuseID])
  }

  // set editor outlet
  setEditorRouterOutlet(laneuseID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gonggantt_go_editor: ["github_com_fullstack_lang_gonggantt_go-" + "laneuse-detail", laneuseID, this.GONG__StackPath]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.laneuses.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.laneuses.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<LaneUseDB>()

      // reset all initial selection of laneuse that belong to laneuse
      for (let laneuse of this.initialSelection) {
        let index = laneuse[this.dialogData.ReversePointer as keyof LaneUseDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(laneuse)

      }

      // from selection, set laneuse that belong to laneuse
      for (let laneuse of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = laneuse[this.dialogData.ReversePointer as keyof LaneUseDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(laneuse)
      }


      // update all laneuse (only update selection & initial selection)
      for (let laneuse of toUpdate) {
        this.laneuseService.updateLaneUse(laneuse)
          .subscribe(laneuse => {
            this.laneuseService.LaneUseServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, LaneUseDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedLaneUse = new Set<number>()
      for (let laneuse of this.initialSelection) {
        if (this.selection.selected.includes(laneuse)) {
          // console.log("laneuse " + laneuse.Name + " is still selected")
        } else {
          console.log("laneuse " + laneuse.Name + " has been unselected")
          unselectedLaneUse.add(laneuse.ID)
          console.log("is unselected " + unselectedLaneUse.has(laneuse.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let laneuse = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as LaneUseDB
      if (unselectedLaneUse.has(laneuse.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<LaneUseDB>) = new Array<LaneUseDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          laneuse => {
            if (!this.initialSelection.includes(laneuse)) {
              // console.log("laneuse " + laneuse.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + laneuse.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = laneuse.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = laneuse.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("laneuse " + laneuse.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<LaneUseDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
