// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { ArrowDB } from '../arrow-db'
import { ArrowService } from '../arrow.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-arrow-sorting',
  templateUrl: './arrow-sorting.component.html',
  styleUrls: ['./arrow-sorting.component.css']
})
export class ArrowSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of Arrow instances that are in the association
  associatedArrows = new Array<ArrowDB>();

  constructor(
    private arrowService: ArrowService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of arrow instances
    public dialogRef: MatDialogRef<ArrowSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getArrows()
  }

  getArrows(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let arrow of this.frontRepo.Arrows_array) {
          let ID = this.dialogData.ID
          let revPointerID = arrow[this.dialogData.ReversePointer]
          let revPointerID_Index = arrow[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedArrows.push(arrow)
          }
        }

        // sort associated arrow according to order
        this.associatedArrows.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedArrows, event.previousIndex, event.currentIndex);

    // set the order of Arrow instances
    let index = 0
    
    for (let arrow of this.associatedArrows) {
      let revPointerID_Index = arrow[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedArrows.forEach(
      arrow => {
        this.arrowService.updateArrow(arrow)
          .subscribe(arrow => {
            this.arrowService.ArrowServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
